### ISSUE TITLE
local position = C_Map.GetPlayerMapPosition(uiMapID, unitToken)

### ISSUE THREAD

**Issue by Ookami313** [SLOKnightfall/DragonridingJournal#2]
Took a character that I had this addon loaded on into Zerith Mortis and received the following error. Thanks.

1x Usage: local position = C_Map.GetPlayerMapPosition(uiMapID, unitToken)
[string "=[C]"]: in function `GetPlayerMapPosition'
[string "@DragonridingJournal/Modules/Races.lua"]:32: in function `GetRaceID'
[string "@DragonridingJournal/Modules/Races.lua"]:259: in function `OnEvent'
[string "@DragonridingJournal/Modules/Races.lua"]:28: in function <DragonridingJournal/Modules/Races.lua:28>

Locals:
(*temporary) = "Usage: local position = C_Map.GetPlayerMapPosition(uiMapID, unitToken)"

**Comment by SLOKnightfall** [comment]
Should be fixed in next update
