### ISSUE TITLE
Races.lua:54: attempt to index local 'data' (a nil value)

### ISSUE THREAD

**Issue by Ookami313** [SLOKnightfall/DragonridingJournal#3]
Was flying between flight points in the Ohn'ahran Plains zone when I flew through what I assume was some sort of zone event taking place. Received the following error. Thanks.

2x DragonridingJournal/Modules/Races.lua:54: attempt to index local 'data' (a nil value)
[string "@DragonridingJournal/Modules/Races.lua"]:54: in function `GetRaceTime'
[string "@DragonridingJournal/DragonridingJournal.lua"]:1064: in function <...eDragonridingJournal/DragonridingJournal.lua:1064>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@FrameXML/EventToastManager.lua"]:278: in function `DisplayToast'
[string "@FrameXML/EventToastManager.lua"]:122: in function <FrameXML/EventToastManager.lua:119>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:363
 initTourGuide = <function> defined @DragonridingJournal/Modules/Guide.lua:531
 modules = <table> {
 }
 baseName = "DragonridingJournal"
 IterateEmbeds = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:438
 SecureHook = <function> defined @TipTac/libs/AceHook-3.0/AceHook-3.0.lua:335
 GetMood = <function> defined @DragonridingJournal/Modules/Bio.lua:43
 Printf = <function> defined @DataStore/libs/AceConsole-3.0/AceConsole-3.0.lua:65
 SetDefaultModulePrototype = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:405
 defaultModuleState = true
 ToggleGuide = <function> defined @DragonridingJournal/Modules/Guide.lua:660
 IsEnabled = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:447
 Frame = <table> {
 }
 ResizeVigorFrame = <function> defined @DragonridingJournal/Modules/Vigor.lua:243
 DisableModule = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:346
 ToggleLinkWindow = <function> defined @DragonridingJournal/Modules/Guide.lua:675
 RegisterMessage = <function> defined @AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:153
 UpdateFonts = <function> defined @DragonridingJournal/Modules/Guide.lua:721
 IsHooked = <function> defined @TipTac/libs/AceHook-3.0/AceHook-3.0.lua:492
 db = <table> {
 }
 fontStrings = <table> {
 }
 SetEnabledState = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 Hook = <function> defined @TipTac/libs/AceHook-3.0/AceHook-3.0.lua:273
 enabledState = true
 RegisterEvent = <function> defined @AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 IterateModules = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:433
 RawHook = <function> defined @TipTac/libs/AceHook-3.0/AceHook-3.0.lua:312
 RemoveVigorBorder = <function> defined @DragonridingJournal/Modules/Vigor.lua:229
 AddDataProvider = <function> defined @DragonridingJournal/Modules/Map.lua:11
 Enable = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:290
 NewModule = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:231
 Data = <table> {
 }
 GetRaceMedal = <function> defined @DragonridingJournal/Modules/Races.lua:100
 GetModule = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:206
 defaultModuleLibraries = <table> {
 }
 optionsFrame = Frame {
 }
 UnregisterChatCommand = <function> defined @DataStore/libs/AceConsole-3.0/AceConsole-3.0.lua:107
 GetName = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:275
 name = "DragonridingJournal"
 currentDragon = 368896
 orderedModules = <table> {
 }
 GetRaceMedalTime = <function> defined @DragonridingJournal/Modules/Races.lua:77
 Disable = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:310
 SecureHookScript = <function> defined @TipTac/libs/AceHook-3.0/AceHook-3.0.lua:409
 GetArgs = <function> defined @DataStore/libs/AceConsole-3.0/AceConsole-3.0.lua:140
 RefreshConfig = <function> defined @DragonridingJournal/DragonridingJournal.lua:1046
 DataBroker = <table> {
 }
 UpdateStatsWindow = <function> defined @DragonridingJournal/Modules/Guide.lua:701
 Unhook = <function> defined @TipTac/libs/AceHook-3.0/AceHook-3.0.lua:417
 Print = <function> defined @DataStore/libs/AceConsole-3.0

**Comment by SLOKnightfall** [comment]
Thanks.  Should be fixed in the next update
